# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-17.10"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.provision "chef_solo" do |chef|
    chef.add_recipe "apache"
  end
end
